version: '3'
services:
  python3:
    restart: always
    build: ./
    container_name: 'python3'
    working_dir: '/sake/backend/src'
    tty: true
    volumes:
      - ..:/sake
    ports:
      - "8000:8000"
