name: Lint by Stylelint

on:
  pull_request:
    paths:
      - 'frontend/src/styles/*.css'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          cd frontend
          yarn install --frozen-lockfile --prefer-offline
      - name: Run Stylelint
        run: |
          cd frontend
          yarn lint:style
