name: Lint by ESLint

on:
  pull_request:
    paths:
      - 'frontend/src/js/*.js'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: ESLint
        run: npm run lint
